apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: online-boutique-dev
namePrefix: dev-

resources:
  - ../../base

commonLabels:
  environment: development

replicas:
  - name: ms-frontend
    count: 1
  - name: ms-cart
    count: 1
  - name: ms-productcatalog
    count: 1
  - name: ms-currency
    count: 1
  - name: ms-payment
    count: 1
  - name: ms-shipping
    count: 1
  - name: ms-email
    count: 1
  - name: ms-checkout
    count: 1
  - name: ms-recommendation
    count: 1
  - name: ms-ad
    count: 1

configMapGenerator:
  - name: online-boutique-config
    literals:
      - ENVIRONMENT=development 